### ISSUE TITLE
Incorrect image on blog entry

### ISSUE THREAD

**Issue by ericthelin** [teegarcs/Runtime_Permissions#1]
The blog entry that points to this example (http://www.captechconsulting.com/blogs/runtime-permissions-best-practices-and-how-to-gracefully-handle-permission-removal) seems to have the wrong image attached. For the last section (before closing) "Suggested Permissions Flow" the image attached is the list of permissions that was referenced at the top of the page instead of what I expect to be a flow diagram.

**Comment by teegarcs** [comment]
Thank you for reaching out. This was a previous issue my webmaster had
fixed and somehow was reverted.  It should be updated as of now.

Again, Thank you for reaching out.

Clinton Teegarden
